In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

In [5]:
OHE=OneHotEncoder()

In [23]:
Countries=pd.read_csv(r"C:\Users\ppawa\Pranav\Study\Engineering\SEM 4\DMA\LabWork\DMA-Codes\countries of the world.csv")
Columns={'Climate','Birthrate','Deathrate','Agriculture','Industry','Service','Net migration','Infant mortality (per 1000 births)','Arable (%)','Crops (%)','Other (%)'}
Countries.drop(Columns,axis=1,inplace=True)
Countries.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),GDP ($ per capita),Literacy (%),Phones (per 1000)
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00",700.0,"36,0","3,2"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26",4500.0,"86,5","71,2"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04",6000.0,"70,0","78,1"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29",8000.0,"97,0","259,5"
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00",19000.0,"100,0","497,2"

In [25]:
Encoded_Countries=OHE.fit_transform(Countries[['Country']]).toarray()
Encoded_Countries

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
C=OHE.get_feature_names_out(['Country'])
C

array(['Country_Afghanistan ', 'Country_Albania ', 'Country_Algeria ',
       'Country_American Samoa ', 'Country_Andorra ', 'Country_Angola ',
       'Country_Anguilla ', 'Country_Antigua & Barbuda ',
       'Country_Argentina ', 'Country_Armenia ', 'Country_Aruba ',
       'Country_Australia ', 'Country_Austria ', 'Country_Azerbaijan ',
       'Country_Bahamas, The ', 'Country_Bahrain ', 'Country_Bangladesh ',
       'Country_Barbados ', 'Country_Belarus ', 'Country_Belgium ',
       'Country_Belize ', 'Country_Benin ', 'Country_Bermuda ',
       'Country_Bhutan ', 'Country_Bolivia ',
       'Country_Bosnia & Herzegovina ', 'Country_Botswana ',
       'Country_Brazil ', 'Country_British Virgin Is. ',
       'Country_Brunei ', 'Country_Bulgaria ', 'Country_Burkina Faso ',
       'Country_Burma ', 'Country_Burundi ', 'Country_Cambodia ',
       'Country_Cameroon ', 'Country_Canada ', 'Country_Cape Verde ',
       'Country_Cayman Islands ', 'Country_Central African Rep. ',
       'Country_Chad ', 'Country_Chile ', 'Country_China ',
       'Country_Colombia ', 'Country_Comoros ',
       'Country_Congo, Dem. Rep. ', 'Country_Congo, Repub. of the ',
       'Country_Cook Islands ', 'Country_Costa Rica ',
       "Country_Cote d'Ivoire ", 'Country_Croatia ', 'Country_Cuba ',
       'Country_Cyprus ', 'Country_Czech Republic ', 'Country_Denmark ',
       'Country_Djibouti ', 'Country_Dominica ',
       'Country_Dominican Republic ', 'Country_East Timor ',
       'Country_Ecuador ', 'Country_Egypt ', 'Country_El Salvador ',
       'Country_Equatorial Guinea ', 'Country_Eritrea ',
       'Country_Estonia ', 'Country_Ethiopia ', 'Country_Faroe Islands ',
       'Country_Fiji ', 'Country_Finland ', 'Country_France ',
       'Country_French Guiana ', 'Country_French Polynesia ',
       'Country_Gabon ', 'Country_Gambia, The ', 'Country_Gaza Strip ',
       'Country_Georgia ', 'Country_Germany ', 'Country_Ghana ',
       'Country_Gibraltar ', 'Country_Greece ', 'Country_Greenland ',
       'Country_Grenada ', 'Country_Guadeloupe ', 'Country_Guam ',
       'Country_Guatemala ', 'Country_Guernsey ', 'Country_Guinea ',
       'Country_Guinea-Bissau ', 'Country_Guyana ', 'Country_Haiti ',
       'Country_Honduras ', 'Country_Hong Kong ', 'Country_Hungary ',
       'Country_Iceland ', 'Country_India ', 'Country_Indonesia ',
       'Country_Iran ', 'Country_Iraq ', 'Country_Ireland ',
       'Country_Isle of Man ', 'Country_Israel ', 'Country_Italy ',
       'Country_Jamaica ', 'Country_Japan ', 'Country_Jersey ',
       'Country_Jordan ', 'Country_Kazakhstan ', 'Country_Kenya ',
       'Country_Kiribati ', 'Country_Korea, North ',
       'Country_Korea, South ', 'Country_Kuwait ', 'Country_Kyrgyzstan ',
       'Country_Laos ', 'Country_Latvia ', 'Country_Lebanon ',
       'Country_Lesotho ', 'Country_Liberia ', 'Country_Libya ',
       'Country_Liechtenstein ', 'Country_Lithuania ',
       'Country_Luxembourg ', 'Country_Macau ', 'Country_Macedonia ',
       'Country_Madagascar ', 'Country_Malawi ', 'Country_Malaysia ',
       'Country_Maldives ', 'Country_Mali ', 'Country_Malta ',
       'Country_Marshall Islands ', 'Country_Martinique ',
       'Country_Mauritania ', 'Country_Mauritius ', 'Country_Mayotte ',
       'Country_Mexico ', 'Country_Micronesia, Fed. St. ',
       'Country_Moldova ', 'Country_Monaco ', 'Country_Mongolia ',
       'Country_Montserrat ', 'Country_Morocco ', 'Country_Mozambique ',
       'Country_N. Mariana Islands ', 'Country_Namibia ',
       'Country_Nauru ', 'Country_Nepal ', 'Country_Netherlands ',
       'Country_Netherlands Antilles ', 'Country_New Caledonia ',
       'Country_New Zealand ', 'Country_Nicaragua ', 'Country_Niger ',
       'Country_Nigeria ', 'Country_Norway ', 'Country_Oman ',
       'Country_Pakistan ', 'Country_Palau ', 'Country_Panama ',
       'Country_Papua New Guinea ', 'Country_Paraguay ', 'Country_Peru ',
       'Country_Philippines ', 'Country_Poland ', 'Country_Portugal ',
       'Country_Puerto Rico ', 'Country_Qatar ', 'Country_Reunion ',
       'Country_Romania ', 'Country_Russia ', 'Country_Rwanda ',
       'Country_Saint Helena ', 'Country_Saint Kitts & Nevis ',
       'Country_Saint Lucia ',
       'Country_Saint Vincent and the Grenadines ', 'Country_Samoa ',
       'Country_San Marino ', 'Country_Sao Tome & Principe ',
       'Country_Saudi Arabia ', 'Country_Senegal ', 'Country_Serbia ',
       'Country_Seychelles ', 'Country_Sierra Leone ',
       'Country_Singapore ', 'Country_Slovakia ', 'Country_Slovenia ',
       'Country_Solomon Islands ', 'Country_Somalia ',
       'Country_South Africa ', 'Country_Spain ', 'Country_Sri Lanka ',
       'Country_St Pierre & Miquelon ', 'Country_Sudan ',
       'Country_Suriname ', 'Country_Swaziland ', 'Country_Sweden ',
       'Country_Switzerland ', 'Country_Syria ', 'Country_Taiwan ',
       'Country_Tajikistan ', 'Country_Tanzania ', 'Country_Thailand ',
       'Country_Togo ', 'Country_Tonga ', 'Country_Trinidad & Tobago ',
       'Country_Tunisia ', 'Country_Turkey ', 'Country_Turkmenistan ',
       'Country_Turks & Caicos Is ', 'Country_Tuvalu ', 'Country_Uganda ',
       'Country_Ukraine ', 'Country_United Arab Emirates ',
       'Country_United Kingdom ', 'Country_United States ',
       'Country_Uruguay ', 'Country_Uzbekistan ', 'Country_Vanuatu ',
       'Country_Venezuela ', 'Country_Vietnam ',
       'Country_Virgin Islands ', 'Country_Wallis and Futuna ',
       'Country_West Bank ', 'Country_Western Sahara ', 'Country_Yemen ',
       'Country_Zambia ', 'Country_Zimbabwe '], dtype=object)

In [29]:
Encoded_CountriesDF=pd.DataFrame(Encoded_Countries, columns=C)
Encoded_CountriesDF

,Country_Afghanistan,Country_Albania,Country_Algeria,Country_American Samoa,Country_Andorra,Country_Angola,Country_Anguilla,Country_Antigua & Barbuda,Country_Argentina,Country_Armenia,...,Country_Vanuatu,Country_Venezuela,Country_Vietnam,Country_Virgin Islands,Country_Wallis and Futuna,Country_West Bank,Country_Western Sahara,Country_Yemen,Country_Zambia,Country_Zimbabwe
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
223,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
224,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
225,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
226,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0